on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Set image tag
          id: vars
          run: echo "IMAGE_TAG=v${{ github.run_number }}" >> $GITHUB_ENV

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . \
              --build-arg REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }} \
              --build-arg REACT_APP_PORT=${{ secrets.REACT_APP_PORT }} \
              --build-arg REACT_APP_INACTIVITY_TIMEOUT=${{ secrets.REACT_APP_INACTIVITY_TIMEOUT }} \
              --build-arg REACT_APP_PRIMARY_COLOR=${{ secrets.REACT_APP_PRIMARY_COLOR }} \
              --build-arg REACT_APP_SECONDARY_COLOR=${{ secrets.REACT_APP_SECONDARY_COLOR }} \
              -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/apa-webapp:${{ env.IMAGE_TAG }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/apa-webapp:${{ env.IMAGE_TAG }}
            
